{% set name = "detecto" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/detecto-{{ version }}.tar.gz
  sha256: 85527a07746df6f26c2bb67e4336357cbcc0ee40e1ef369519a8aeb3ebf60300

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - opencv
    - pandas
    - python >={{ python_min }}
    - pytorch
    - torchvision
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - detecto
    - detecto.tests

about:
  home: https://github.com/alankbi/detecto
  summary: Build fully-functioning computer vision models with PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://detecto.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
